//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 

namespace EInv.Models.EInv.v32.B2BEX.Allowance
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:GEINV:eInvoiceMessage:B0102:3.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:GEINV:eInvoiceMessage:B0102:3.2", IsNullable = false)]
    public partial class AllowanceConfirm
    {

        private string allowanceNumberField;

        private string allowanceDateField;

        private string buyerIdField;

        private string sellerIdField;

        private string receiveDateField;

        private System.DateTime receiveTimeField;

        private AllowanceTypeEnum allowanceTypeField;

        private string remarkField;

        /// <remarks/>
        public string AllowanceNumber
        {
            get
            {
                return this.allowanceNumberField;
            }
            set
            {
                this.allowanceNumberField = value;
            }
        }

        /// <remarks/>
        public string AllowanceDate
        {
            get
            {
                return this.allowanceDateField;
            }
            set
            {
                this.allowanceDateField = value;
            }
        }

        /// <remarks/>
        public string BuyerId
        {
            get
            {
                return this.buyerIdField;
            }
            set
            {
                this.buyerIdField = value;
            }
        }

        /// <remarks/>
        public string SellerId
        {
            get
            {
                return this.sellerIdField;
            }
            set
            {
                this.sellerIdField = value;
            }
        }

        /// <remarks/>
        public string ReceiveDate
        {
            get
            {
                return this.receiveDateField;
            }
            set
            {
                this.receiveDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime ReceiveTime
        {
            get
            {
                return this.receiveTimeField;
            }
            set
            {
                this.receiveTimeField = value;
            }
        }

        /// <remarks/>
        public AllowanceTypeEnum AllowanceType
        {
            get
            {
                return this.allowanceTypeField;
            }
            set
            {
                this.allowanceTypeField = value;
            }
        }

        /// <remarks/>
        public string Remark
        {
            get
            {
                return this.remarkField;
            }
            set
            {
                this.remarkField = value;
            }
        }
    }

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    //[System.SerializableAttribute()]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:GEINV:eInvoiceMessage:B0102:3.2")]
    //public enum AllowanceTypeEnum
    //{

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlEnumAttribute("1")]
    //    Item1,

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlEnumAttribute("2")]
    //    Item2,
    //}
}