//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 

namespace EInv.Models.EInv.v32.B2C.EInvoice
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:GEINV:eInvoiceMessage:C0701:3.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:GEINV:eInvoiceMessage:C0701:3.2", IsNullable = false)]
    [Table("C0701", Schema = "EInv")]
    public partial class VoidInvoice
    {
        [Key]
        public Guid Id { get; set; }

        private string voidInvoiceNumberField;

        private string invoiceDateField;

        private string buyerIdField;

        private string sellerIdField;

        private string voidDateField;

        private System.DateTime voidTimeField;

        private string voidReasonField;

        private string remarkField;

        /// <remarks/>
        public string VoidInvoiceNumber
        {
            get
            {
                return this.voidInvoiceNumberField;
            }
            set
            {
                this.voidInvoiceNumberField = value;
            }
        }

        /// <remarks/>
        public string InvoiceDate
        {
            get
            {
                return this.invoiceDateField;
            }
            set
            {
                this.invoiceDateField = value;
            }
        }

        /// <remarks/>
        public string BuyerId
        {
            get
            {
                return this.buyerIdField;
            }
            set
            {
                this.buyerIdField = value;
            }
        }

        /// <remarks/>
        public string SellerId
        {
            get
            {
                return this.sellerIdField;
            }
            set
            {
                this.sellerIdField = value;
            }
        }

        /// <remarks/>
        public string VoidDate
        {
            get
            {
                return this.voidDateField;
            }
            set
            {
                this.voidDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime VoidTime
        {
            get
            {
                return this.voidTimeField;
            }
            set
            {
                this.voidTimeField = value;
            }
        }

        /// <remarks/>
        public string VoidReason
        {
            get
            {
                return this.voidReasonField;
            }
            set
            {
                this.voidReasonField = value;
            }
        }

        /// <remarks/>
        public string Remark
        {
            get
            {
                return this.remarkField;
            }
            set
            {
                this.remarkField = value;
            }
        }
    }
}