//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 

namespace EInvLib.Models.EInv.v32.B2C.Allowance
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:GEINV:eInvoiceMessage:D0501:3.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:GEINV:eInvoiceMessage:D0501:3.2", IsNullable = false)]
    [Table("D0501", Schema = "EInv")]
    public partial class CancelAllowance
    {
        [Key]
        public Guid Id { get; set; }

        private string cancelAllowanceNumberField;

        private string allowanceDateField;

        private string buyerIdField;

        private string sellerIdField;

        private string cancelDateField;

        private System.DateTime cancelTimeField;

        private string cancelReasonField;

        private string remarkField;

        /// <remarks/>
        public string CancelAllowanceNumber
        {
            get
            {
                return this.cancelAllowanceNumberField;
            }
            set
            {
                this.cancelAllowanceNumberField = value;
            }
        }

        /// <remarks/>
        public string AllowanceDate
        {
            get
            {
                return this.allowanceDateField;
            }
            set
            {
                this.allowanceDateField = value;
            }
        }

        /// <remarks/>
        public string BuyerId
        {
            get
            {
                return this.buyerIdField;
            }
            set
            {
                this.buyerIdField = value;
            }
        }

        /// <remarks/>
        public string SellerId
        {
            get
            {
                return this.sellerIdField;
            }
            set
            {
                this.sellerIdField = value;
            }
        }

        /// <remarks/>
        public string CancelDate
        {
            get
            {
                return this.cancelDateField;
            }
            set
            {
                this.cancelDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime CancelTime
        {
            get
            {
                return this.cancelTimeField;
            }
            set
            {
                this.cancelTimeField = value;
            }
        }

        /// <remarks/>
        public string CancelReason
        {
            get
            {
                return this.cancelReasonField;
            }
            set
            {
                this.cancelReasonField = value;
            }
        }

        /// <remarks/>
        public string Remark
        {
            get
            {
                return this.remarkField;
            }
            set
            {
                this.remarkField = value;
            }
        }
    }
}