//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 

namespace EInvLib.Models.EInv.v32.B2P.E0401
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:GEINV:eInvoiceMessage:E0401:3.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:GEINV:eInvoiceMessage:E0401:3.2", IsNullable = false)]
    [Table("E0401", Schema = "EInv")]
    public partial class BranchTrack
    {
        [Key]
        public Guid Id { get; set; }
        private Main mainField;

        private DetailsBranchTrackItem[] detailsField;

        /// <remarks/>
        public Main Main
        {
            get
            {
                return this.mainField;
            }
            set
            {
                this.mainField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("BranchTrackItem", IsNullable = false)]
        public DetailsBranchTrackItem[] Details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:GEINV:eInvoiceMessage:E0401:3.2")]
    [Table("E0401_Main", Schema = "EInv")]
    public partial class Main
    {
        [Key]
        public Guid Id { get; set; }

        private string headBanField;

        private string branchBanField;

        private InvoiceTypeEnum invoiceTypeField;

        private string yearMonthField;

        private string invoiceTrackField;

        private string invoiceBeginNoField;

        private string invoiceEndNoField;

        /// <remarks/>
        public string HeadBan
        {
            get
            {
                return this.headBanField;
            }
            set
            {
                this.headBanField = value;
            }
        }

        /// <remarks/>
        public string BranchBan
        {
            get
            {
                return this.branchBanField;
            }
            set
            {
                this.branchBanField = value;
            }
        }

        /// <remarks/>
        public InvoiceTypeEnum InvoiceType
        {
            get
            {
                return this.invoiceTypeField;
            }
            set
            {
                this.invoiceTypeField = value;
            }
        }

        /// <remarks/>
        public string YearMonth
        {
            get
            {
                return this.yearMonthField;
            }
            set
            {
                this.yearMonthField = value;
            }
        }

        /// <remarks/>
        public string InvoiceTrack
        {
            get
            {
                return this.invoiceTrackField;
            }
            set
            {
                this.invoiceTrackField = value;
            }
        }

        /// <remarks/>
        public string InvoiceBeginNo
        {
            get
            {
                return this.invoiceBeginNoField;
            }
            set
            {
                this.invoiceBeginNoField = value;
            }
        }

        /// <remarks/>
        public string InvoiceEndNo
        {
            get
            {
                return this.invoiceEndNoField;
            }
            set
            {
                this.invoiceEndNoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:GEINV:eInvoiceMessage:E0401:3.2")]
    public enum InvoiceTypeEnum
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:GEINV:eInvoiceMessage:E0401:3.2")]
    [Table("E0401_DetailsBranchTrackItem", Schema = "EInv")]
    public partial class DetailsBranchTrackItem
    {
        [Key]
        public Guid Id { get; set; }

        private string invoiceBeginNoField;

        private string invoiceEndNoField;

        private long invoiceBookletField;

        /// <remarks/>
        public string InvoiceBeginNo
        {
            get
            {
                return this.invoiceBeginNoField;
            }
            set
            {
                this.invoiceBeginNoField = value;
            }
        }

        /// <remarks/>
        public string InvoiceEndNo
        {
            get
            {
                return this.invoiceEndNoField;
            }
            set
            {
                this.invoiceEndNoField = value;
            }
        }

        /// <remarks/>
        public long InvoiceBooklet
        {
            get
            {
                return this.invoiceBookletField;
            }
            set
            {
                this.invoiceBookletField = value;
            }
        }
    }
}