//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 

namespace EInv.Models.EInv.v32.B2BST.EInvoice
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:GEINV:eInvoiceMessage:A0601:3.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:GEINV:eInvoiceMessage:A0601:3.2", IsNullable = false)]
    public partial class RejectInvoice
    {

        private string rejectInvoiceNumberField;

        private string invoiceDateField;

        private string buyerIdField;

        private string sellerIdField;

        private string rejectDateField;

        private System.DateTime rejectTimeField;

        private string rejectReasonField;

        private string remarkField;

        /// <remarks/>
        public string RejectInvoiceNumber
        {
            get
            {
                return this.rejectInvoiceNumberField;
            }
            set
            {
                this.rejectInvoiceNumberField = value;
            }
        }

        /// <remarks/>
        public string InvoiceDate
        {
            get
            {
                return this.invoiceDateField;
            }
            set
            {
                this.invoiceDateField = value;
            }
        }

        /// <remarks/>
        public string BuyerId
        {
            get
            {
                return this.buyerIdField;
            }
            set
            {
                this.buyerIdField = value;
            }
        }

        /// <remarks/>
        public string SellerId
        {
            get
            {
                return this.sellerIdField;
            }
            set
            {
                this.sellerIdField = value;
            }
        }

        /// <remarks/>
        public string RejectDate
        {
            get
            {
                return this.rejectDateField;
            }
            set
            {
                this.rejectDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime RejectTime
        {
            get
            {
                return this.rejectTimeField;
            }
            set
            {
                this.rejectTimeField = value;
            }
        }

        /// <remarks/>
        public string RejectReason
        {
            get
            {
                return this.rejectReasonField;
            }
            set
            {
                this.rejectReasonField = value;
            }
        }

        /// <remarks/>
        public string Remark
        {
            get
            {
                return this.remarkField;
            }
            set
            {
                this.remarkField = value;
            }
        }
    }
}